controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\RegisterForm;
use app\models\Books;
use app\models\Authors;
use app\models\User;
use app\models\ProfileForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    /**
     * Displays register page.
     *
     * @return string
     */
    public function actionRegister(){
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new RegisterForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->actionProfile();
                }
            }
        }
        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionBooks(){
        $model = new Books();
        $array = $model->find()->innerjoinWith('author')->all();
        return $this->render('books', [
            'array' => $array
        ]);
    }
    public function actionAddbook($id){
        $books = new Books();
        $books->load(Yii::$app->request->post());
        $books->id_user = $id;
        $books->save();
        return $this->actionProfile();
    }
    public function actionDeletebook($id){
        Books::deleteAll(['id' => $id]);
        return $this->actionProfile();
    }
    public function actionUpdatebook($id){
        $model = Books::findOne($id);
        if($model->load(Yii::$app->request->post())){
            $model->save();
        }
        /**  $model->Text*/
        return $this->actionProfile();
    }
    public function actionAuthors(){
        $model = new Authors();
        $array = $model->find()->joinWith('books')->all();
        return $this->render('authors', [
            'array' => $array,
        ]);
    }

    public function  actionProfile(){
        $books = new Books();
        $model = new ProfileForm();
        $array = $books->find()->where(['id_user' => Yii::$app->user->identity->id])->all();
        return $this->render('profile', [
            'model' => $model,
            'array' => $array,
            'book' => $books,
        ]);
    }
    public function  actionSetfirst(){
        $model = User::find()->where(['username' => 'admin'])->one();
        if (empty($model)) {
            $user = new User();
            $user->username = 'admin';
            $user->email = 'nicker47@mail.ru';
            $user->setPassword('admin');
            $user->generateAuthKey();
            if ($user->save()) {
                echo 'good';
            }
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/authors.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $array app\models\Authors */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Authors';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clearfix"></div>
<hr />
<table class="table table-striped table-hover">
    <tr>
        <td>#</td>
        <td>Author</td>
        <td>Photo</td>
        <td>Description</td>
        <td>Books count</td>
    </tr>
    <?php foreach ($array as $arr): ?>
        <tr>
            <td>
                <?php echo Html::a($arr->id, array('site/profile', 'id'=>$arr->id)); ?>
            </td>
            <td><?php echo Html::a($arr->username, array('site/profile', 'id'=>$arr->id)); ?></td>
            <td><?php echo Html::a(Html::img($arr->photo, ['alt' => $arr->username, 'width' => 100]), array('site/profile', 'id'=>$arr->id)); ?></td>
            <td><?php echo $arr->description; ?></td>
            <td><?php echo count($arr->books) ?></td>

        </tr>
    <?php endforeach; ?>
</table>

views/site/books.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $array app\models\Books */


use app\models\Books;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Books';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="clearfix"></div>
<hr />
<table class="table table-striped table-hover">
    <tr>
        <td>#</td>
        <td>Author</td>
        <td>Title</td>
        <td>Genres</td>
        <td>Description</td>
    </tr>
    <?php foreach ($array as $arr): ?>
        <tr>
            <td>
                <?php echo Html::a($arr->id, array('site/book', 'id'=>$arr->id)); ?>
            </td>
            <td><?php echo Html::a($arr->author->username, array('site/profile', 'id'=>$arr->id_user)); ?></td>
            <td><?php echo Html::a($arr->name, array('site/book', 'id'=>$arr->id)); ?></td>
            <td><?php echo Html::a($arr->genres, array('site/book', 'genre'=>$arr->genres)); ?></td>
            <td><?php echo $arr->Text; ?></td>
        </tr>
    <?php endforeach; ?>
</table>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application Test';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Login';

/* */
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?> or <a href="<?= Url::to(['/site/register'])?>">Create a new account</a></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/profile.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ProfileForm */
/* @var $array app\models\ProfileForm */
/* @var $book app\models\ProfileForm */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\bootstrap\Modal;

$this->title = 'Profile - '.Yii::$app->user->identity->username.'';

?>
<div class="container bootstrap snippet">
    <div class="row">
        <div class="col-sm-10"><h1><?php echo Yii::$app->user->identity->username; ?></h1></div>
        <div class="col-sm-2"><?php
            echo Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Exit',
                ['class' => 'btn btn-danger logout']
            )
            . Html::endForm()
            ?></div>
    </div>
    <div class="row">
        <div class="col-sm-3"><!--left col-->

            <div class="text-center">

                <?php echo Html::img(Yii::$app->user->identity->photo, $options = ['class' => 'postImg avatar img-circle img-thumbnail', 'style' => ['alt' => Yii::$app->user->identity->username]]); ?>

                <form id="uploadPhoto">
                    <input id="myPhoto" type="file" name="myPhoto"/>
                    <input type="submit" value="Uload">
                </form>
            </div></hr><br>

        </div><!--/col-3-->
        <div class="col-sm-9">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#settings">Settings</a></li>
                <li><a data-toggle="tab" href="#books">Books</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="settings">
                    <hr>
                    <?php $form = ActiveForm::begin(['id' => 'profile-form']); ?>

                        <div class="form-group">

                            <div class="col-xs-6">
                                <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'value' => Yii::$app->user->identity->username]) ?>
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-xs-6">
                                <?= $form->field($model, 'email')->textInput(['value' => Yii::$app->user->identity->email]) ?>
                            </div>
                        </div>
                        <div class="form-group">

                            <div class="col-xs-6">
                                <?= $form->field($model, 'password')->passwordInput() ?>
                            </div>
                        </div>
                        <div class="form-group">

                            <div class="col-xs-6">
                                <?= $form->field($model, 'verify')->passwordInput() ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <?= $form->field($model, 'about')->textarea(['rows' => '6']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <br>
                                <button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Update</button>
                            </div>
                        </div>

                    <?php ActiveForm::end(); ?>

                    <hr>

                </div><!--/tab-pane-->
                <div class="tab-pane" id="books">

                    <div class="clearfix"></div>
                    <hr />
                    <table class="table table-striped table-hover">
                        <label>Your books</label>
                        <tr>
                            <td>#</td>
                            <td>Title</td>
                            <td>Genres</td>
                            <td>Description</td>
                            <td></td>
                        </tr>
                        <?php foreach ($array as $arr): ?>
                            <tr>
                                <td>
                                    <?php echo Html::a($arr->id, array('site/book', 'id'=>$arr->id)); ?>
                                </td>
                                <td><?php echo Html::a($arr->name, array('site/book', 'id'=>$arr->id)); ?></td>
                                <td><?php echo Html::a($arr->genres, array('site/book', 'genre'=>$arr->genres)); ?></td>
                                <td><?php echo $arr->Text; ?></td>
                                <?php  if(!Yii::$app->user->isGuest) : ?>
                                    <td>
                                        <?php echo Html::a('Remove', array('site/deletebook', 'id'=>$arr->id), array('class'=>'btn btn-primary pull-right')); ?>
                                        <?php Modal::begin([
                                            'header' => 'Change book',
                                            'size' => 'modal-lg',
                                            'toggleButton' => [
                                            'label' => 'Change',
                                            'class' => 'btn btn-secondary pull-right'
                                        ],
                                        'footer' => Yii::$app->user->identity->username,
                                        ]);
                                        $form = ActiveForm::begin(['action' => ['site/updatebook', 'id'=>$arr->id]]);
                                        echo $form->field($book, 'name')->textInput(['autofocus' => true, 'value' => $arr->name])->label('Title');
                                        echo $form->field($book, 'genres')->textInput(['value' => $arr->genres])->label('Genres');
                                        echo $form->field($book, 'Text')->textarea(['rows' => '6', 'value' => $arr->Text])->label('Description') ;

                                        echo Html::submitButton('Change', ['class' => 'btn btn-primary', 'name' => 'changeBook-button']);

                                        ActiveForm::end();
                                        Modal::end();?>

                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                    <?php Modal::begin([
                        'header' => '<h2>Create New Book</h2>',
                        'size' => 'modal-lg',
                        'toggleButton' => [
                                'label' => 'Create New Book',
                                'class' => 'btn btn-primary pull-right'
                        ],
                        'footer' => Yii::$app->user->identity->username,
                    ]);
                    $form = ActiveForm::begin(['action' => ['site/addbook', 'id'=>Yii::$app->user->identity->id]]);
                    echo $form->field($book, 'name')->textInput(['autofocus' => true])->label('Title');
                    echo $form->field($book, 'genres')->textInput()->label('Genres')->label('Genres');
                    echo $form->field($book, 'Text')->textarea(['rows' => '6'])->label('Description');

                    echo Html::submitButton('Create Book', ['class' => 'btn btn-primary', 'name' => 'login-button']);

                    ActiveForm::end();
                    ?>
                    <?php Modal::end(); ?>
                </div><!--/tab-pane-->
            </div><!--/tab-pane-->
        </div><!--/tab-content-->

    </div><!--/col-9-->

</div>

views/site/register.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\RegisterForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Url;

$this->title = 'Registration';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-register">
    <h1><?= Html::encode($this->title) ?> or <a href="<?= Url::to(['/site/login'])?>">Login to your account</a></h1>
    <p>Please fill out the following fields to registration:</p>
    <?php if (Yii::$app->user->isGuest) : ?>
        <div class="row">
            <div class="col-lg-5">
                <?php $form = ActiveForm::begin(['id' => 'register-form']); ?>
                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'sendUpdates')->checkbox([
                    'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    'checked' => true,
                ]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <div class="col-lg-offset-1 col-lg-11">
                        <?= Html::submitButton('Create Account', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                    </div>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    <?php else: ?>
        You are already logged in to the site.
    <?php endif; ?>
</div>